### ISSUE TITLE
Nueva entidad: Cliente

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/imb.pr3.gc.2023.hotel.spring#2]
Se requiere crear una nueva entidad denominada `Cliente` la cual debe contar con los siguientes atributos:

 - id (Integer)
 - apellido (String)
 - nombre (String)
 - fechaDeNacimiento (DateTime)
 - domicilio (String)
 - email (String)
 - telefono (String)

En el controller, se deben generar los siguientes métodos:
 
 - obtenerTodosLosClientes (GET)
 - obtenerClientesPorId (GET)
 - crearCliente (POST)
 - modificarCliente (PUT)
 - eliminarCliente (DELETE)

**Comment by Argioz** [comment]
Postman arroja este mensaje por la consola. El body que está devolviendo se corresponde al de un proyecto anterior en el que trabajé. No encuentro en el código algo que haga la conexión con esa base de datos, ya que modifiqué tal conexión en el application.properties
Voy a seguir buscando, pero escucho recomendaciones.

![image](https://github.com/ahumadamob/imb.pr3.gc.2023.hotel.spring/assets/93400273/f4ec13c2-62dd-4c74-87a1-bedf7f5e6944)

**Comment by ahumadamob** [comment]
Estuve viendo tu rama y al parecer no parte bien desde el proyecto que yo dejé en la master. Te recomiendo hacer un proyecto nuevo y trasladar los archivos desde aquí. Sólo los .java

**Comment by Argioz** [comment]
Perfecto. Eso haré. Muchas gracias!

**Comment by Argioz** [comment]
¡Listo! Ya pude solucionarlo.
También lo pusheé sobre la rama que creó usted, profe. Pude levantarlo en STS (con problemas que logré solucionar) y probarlo perfectamente en Postman creando efectivamente los registros en dbeaver. Funcionan perfectamenta las annotations y el manejo de errores, no permitiendo teléfonos de menos de 13 dígitos o coreos sin arroba.
Gracias por la idea de reiniciar, creo que el problema estaba en las rutas de las carpetas.
Un saludo.
![image](https://github.com/ahumadamob/imb.pr3.gc.2023.hotel.spring/assets/93400273/ac0a1e89-a730-4e8d-a138-f7c7affdea96)

**Comment by ahumadamob** [comment]
Está listo el pull request?

**Comment by Argioz** [comment]
Ahí logré hacer el pull request!
